In [ ]:
!pip install torch torchvision
!pip install scikit-learn
!pip install grad-cam
!pip install monai

In [ ]:
#Import all of the necessary libraries for modeling and computing evaluation metrics
import os
import copy
import numpy as np
import pandas as pd
from PIL import Image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from monai.networks.nets import DenseNet121
import pickle

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
import matplotlib.pyplot as plt
import random
from tqdm import tqdm
import time
random.seed(42)

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

In [ ]:
#Use these objects early before creating the model, so that you can easily change CSV path, image directory and other model specific comparisons
CSV_PATH = "/Users/harryshield/Documents/Data Science/DS4002/Project 3/cleaned_data.csv"
IMAGE_DIR = "/Users/harryshield/Documents/Data Science/DS4002/Project 3/ISIC 2020 Images"
OUTPUT_DIR = '/Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet'
NUM_FOLDS = 5
BATCH_SIZE = 128
NUM_EPOCHS = 5
LEARNING_RATE = 1e-4
IMAGE_SIZE = 224
NUM_WORKERS = 0
RANDOM_SEED = 42
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

USE_POS_WEIGHT = True
#Uses the same random seed whenever needs to be used
torch.manual_seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
os.makedirs(OUTPUT_DIR, exist_ok=True)

In [ ]:
#This is defining the model so that PyTorch is able to pull the images from the image directory and match it with identifiers that are in the csv dataset
class SkinLesionDataset(Dataset):
    def __init__(self, dataframe, image_dir, transform=None):
        self.df = dataframe.reset_index(drop=True).copy()
        self.image_dir = image_dir
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        image_path = os.path.join(self.image_dir, str(row["image_name"]) + ".jpg")
        label = float(row["target"])

        image = Image.open(image_path).convert("RGB")

        if self.transform is not None:
            image = self.transform(image)

        return image, torch.tensor(label, dtype=torch.float32)
#Turns all of the images to a specific size for consistency   
train_transform = transforms.Compose([
    transforms.RandomResizedCrop(IMAGE_SIZE, scale=(0.9,1.0)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5],
                         std=[0.5, 0.5, 0.5])
])

val_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5],
                         std=[0.5, 0.5, 0.5])
])
#Where the model is actually determined depending on the pre-trained model being used. In this case it is the DenseNet121
def build_model():
    model = DenseNet121(
        spatial_dims=2,
        in_channels=3,
        out_channels=1
    )
    return model

def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    running_loss = 0.0

    for images, labels in tqdm(loader, desc="Training", leave=False):
        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()
        logits = model(images).squeeze(1)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)

    return running_loss / len(loader.dataset)

@torch.no_grad()
def evaluate(model, loader, criterion, device, threshold=0.39):
    model.eval()
    running_loss = 0.0

    all_labels = []
    all_probs = []

    for images, labels in tqdm(loader, desc="Validation", leave=False):
        images = images.to(device)
        labels = labels.to(device)

        logits = model(images).squeeze(1)
        loss = criterion(logits, labels)

        probs = torch.sigmoid(logits)

        running_loss += loss.item() * images.size(0)
        all_labels.extend(labels.cpu().numpy())
        all_probs.extend(probs.cpu().numpy())

    all_labels = np.array(all_labels)
    all_probs = np.array(all_probs)
    all_preds = (all_probs >= threshold).astype(int)
#Runs the evaluation metrics on how well the model is training and validating results
    metrics = {
        "loss": running_loss / len(loader.dataset),
        "accuracy": accuracy_score(all_labels, all_preds),
        "precision": precision_score(all_labels, all_preds, zero_division=0),
        "recall": recall_score(all_labels, all_preds, zero_division=0),
        "f1": f1_score(all_labels, all_preds, zero_division=0),
        "roc_auc": roc_auc_score(all_labels, all_probs) if len(np.unique(all_labels)) > 1 else np.nan,
        "confusion_matrix": confusion_matrix(all_labels, all_preds)
    }

    return metrics

In [ ]:
def main():
    df = pd.read_csv(CSV_PATH)

    # Basic checks
    required_cols = {"image_name", "target"}
    if not required_cols.issubset(df.columns):
        raise ValueError(f"CSV must contain columns: {required_cols}")

    df = df.dropna(subset=["image_name", "target"]).copy()
    df["target"] = df["target"].astype(int)

    # Make sure files exist
    df["exists"] = df["image_name"].apply(
    lambda x: os.path.exists(os.path.join(IMAGE_DIR, str(x) + ".jpg")))
    missing = df.loc[~df["exists"], "image_name"].tolist()
    if missing:
        print(f"Warning: {len(missing)} images are missing. They will be dropped.")
        df = df[df["exists"]].copy()


    df = df.drop(columns="exists").reset_index(drop=True)

    X = df["image_name"].values
    y = df["target"].values
#This splits the dataset into 5 identical folds that can be used in all of the models and then these folds can be compared in statistical tests
    if not os.path.exists("folds.pkl"):
        print("Creating new folds...")

        skf = StratifiedKFold(n_splits=NUM_FOLDS, shuffle=True, random_state=RANDOM_SEED)
        folds = list(skf.split(X, y))

        with open("folds.pkl", "wb") as f:
            pickle.dump(folds, f)
    else:
        print("Loading existing folds...")
        with open("folds.pkl", "rb") as f:
            folds = pickle.load(f)

    fold_results = []
#Helps tell how much time is left within the model running
    start_time = time.time()

    for fold, (train_idx, val_idx) in enumerate(folds, start=1):
        fold_start = time.time()
        print(f"\n========== Fold {fold}/{NUM_FOLDS} ==========")
    

        train_df = df.iloc[train_idx].copy()
        val_df = df.iloc[val_idx].copy()
#Making sure there is a training and a validation dataset for each of the folds
        train_dataset = SkinLesionDataset(train_df, IMAGE_DIR, transform=train_transform)
        val_dataset = SkinLesionDataset(val_df, IMAGE_DIR, transform=val_transform)

        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            shuffle=True,
            num_workers=NUM_WORKERS
        )

        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=NUM_WORKERS
        )

        model = build_model().to(DEVICE)

        # Handle imbalance
        if USE_POS_WEIGHT:
            num_pos = (train_df["target"] == 1).sum()
            num_neg = (train_df["target"] == 0).sum()

            if num_pos > 0:
                pos_weight_value = num_neg / num_pos
                pos_weight = torch.tensor([pos_weight_value], dtype=torch.float32).to(DEVICE)
                criterion = nn.BCEWithLogitsLoss()
            else:
                criterion = nn.BCEWithLogitsLoss()
        else:
            criterion = nn.BCEWithLogitsLoss()

        optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)

        best_model_wts = copy.deepcopy(model.state_dict())
        best_f1 = -1.0

        for epoch in tqdm(range(NUM_EPOCHS), desc=f"Fold {fold} - Epochs"):
            train_loss = train_one_epoch(model, train_loader, optimizer, criterion, DEVICE)
            val_metrics = evaluate(model, val_loader, criterion, DEVICE)

            print(
                f"Epoch {epoch+1}/{NUM_EPOCHS} | "
                f"Train Loss: {train_loss:.4f} | "
                f"Val Loss: {val_metrics['loss']:.4f} | "
                f"Val Acc: {val_metrics['accuracy']:.4f} | "
                f"Val Recall: {val_metrics['recall']:.4f} | "
                f"Val F1: {val_metrics['f1']:.4f} | "
                f"Val AUC: {val_metrics['roc_auc']:.4f}"
            )

            if val_metrics["f1"] > best_f1:
                best_f1 = val_metrics["f1"]
                best_model_wts = copy.deepcopy(model.state_dict())

        model.load_state_dict(best_model_wts)
        final_metrics = evaluate(model, val_loader, criterion, DEVICE)

        model.eval()

# pick 1 sample from validation set
        fold_dir = os.path.join(OUTPUT_DIR, f"fold_{fold}")
        os.makedirs(fold_dir, exist_ok=True)
        
        NUM_SAMPLES_TO_SAVE = 5

# reproducible randomness per fold
        random.seed(42 + fold)

        indices = random.sample(
            range(len(val_dataset)),
            k=min(NUM_SAMPLES_TO_SAVE, len(val_dataset))
)
#Places GradCAM heatmaps over the image, to show where the model is placing specific importance
        for i in indices:
            sample_img, sample_label = val_dataset[i]
            input_tensor = sample_img.unsqueeze(0).to(DEVICE)

            rgb_img = sample_img.permute(1, 2, 0).cpu().numpy()
            mean = np.array([0.485, 0.456, 0.406])
            std = np.array([0.229, 0.224, 0.225])
            rgb_img = (rgb_img * std) + mean
            rgb_img = np.clip(rgb_img, 0, 1)

            logits = model(input_tensor)
            prob = torch.sigmoid(logits).item()
            pred = int(prob >= 0.39)

            target_layers = [model.features[-1]]
            targets = [ClassifierOutputTarget(0)]

            with GradCAM(model=model, target_layers=target_layers) as cam:
                grayscale_cam = cam(input_tensor=input_tensor, targets=targets)[0]

            visualization = show_cam_on_image(rgb_img, grayscale_cam, use_rgb=True)

            filename = f"fold_{fold}_img_{i}_true_{int(sample_label.item())}_pred_{pred}_prob_{prob:.2f}.png"
            save_path = os.path.join(fold_dir, filename)

            print("Saving to:", save_path)

            plt.figure(figsize=(4, 4))
            plt.imshow(visualization)
            plt.title(f"Fold {fold} | T:{int(sample_label.item())} P:{pred} ({prob:.2f})")
            plt.axis("off")
            plt.savefig(save_path, bbox_inches="tight")
            plt.close()
#Showing all of the evaluation metrics
        print("\nBest fold metrics:")
        print(f"Accuracy:  {final_metrics['accuracy']:.4f}")
        print(f"Precision: {final_metrics['precision']:.4f}")
        print(f"Recall:    {final_metrics['recall']:.4f}")
        print(f"F1:        {final_metrics['f1']:.4f}")
        print(f"ROC-AUC:   {final_metrics['roc_auc']:.4f}")
        print("Confusion Matrix:")
        print(final_metrics["confusion_matrix"])

            # Fold timing
        fold_time = time.time() - fold_start
        print(f"\nFold {fold} time: {fold_time/60:.2f} minutes")

        # Total + ETA
        elapsed = time.time() - start_time
        avg_time_per_fold = elapsed / fold
        remaining_folds = NUM_FOLDS - fold
        eta = avg_time_per_fold * remaining_folds

        print(f"Elapsed time: {elapsed/60:.2f} minutes")
        print(f"Estimated time remaining: {eta/60:.2f} minutes")

        fold_results.append(final_metrics)

    # Average across folds
    avg_accuracy = np.mean([r["accuracy"] for r in fold_results])
    avg_precision = np.mean([r["precision"] for r in fold_results])
    avg_recall = np.mean([r["recall"] for r in fold_results])
    avg_f1 = np.mean([r["f1"] for r in fold_results])
    avg_auc = np.nanmean([r["roc_auc"] for r in fold_results])

    print("\n========== CROSS-VALIDATION SUMMARY ==========")
    print(f"Mean Accuracy:  {avg_accuracy:.4f}")
    print(f"Mean Precision: {avg_precision:.4f}")
    print(f"Mean Recall:    {avg_recall:.4f}")
    print(f"Mean F1:        {avg_f1:.4f}")
    print(f"Mean ROC-AUC:   {avg_auc:.4f}")

if __name__ == "__main__":
    main()

Loading existing folds...

========== Fold 1/5 ==========


Fold 1 - Epochs:  20%|██        | 1/5 [09:06<36:24, 546.04s/it]

Epoch 1/5 | Train Loss: 0.5909 | Val Loss: 0.6091 | Val Acc: 0.6826 | Val Recall: 0.9565 | Val F1: 0.7509 | Val AUC: 0.7653


Fold 1 - Epochs:  40%|████      | 2/5 [17:29<26:03, 521.02s/it]

Epoch 2/5 | Train Loss: 0.5171 | Val Loss: 0.5236 | Val Acc: 0.7478 | Val Recall: 0.8783 | Val F1: 0.7769 | Val AUC: 0.8153


Fold 1 - Epochs:  60%|██████    | 3/5 [26:09<17:21, 520.52s/it]

Epoch 3/5 | Train Loss: 0.4773 | Val Loss: 0.5117 | Val Acc: 0.7522 | Val Recall: 0.8522 | Val F1: 0.7747 | Val AUC: 0.8245


Fold 1 - Epochs:  80%|████████  | 4/5 [35:18<08:51, 531.86s/it]

Epoch 4/5 | Train Loss: 0.4691 | Val Loss: 0.5066 | Val Acc: 0.7652 | Val Recall: 0.8000 | Val F1: 0.7731 | Val AUC: 0.8306


Fold 1 - Epochs: 100%|██████████| 5/5 [42:05<00:00, 505.02s/it]


Epoch 5/5 | Train Loss: 0.4435 | Val Loss: 0.4846 | Val Acc: 0.7565 | Val Recall: 0.8696 | Val F1: 0.7812 | Val AUC: 0.8349


Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_1/fold_1_img_9_true_0_pred_0_prob_0.01.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_1/fold_1_img_73_true_1_pred_0_prob_0.03.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_1/fold_1_img_178_true_1_pred_1_prob_0.60.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_1/fold_1_img_195_true_1_pred_1_prob_0.83.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_1/fold_1_img_36_true_0_pred_0_prob_0.14.png

Best fold metrics:
Accuracy:  0.7565
Precision: 0.7092
Recall:    0.8696
F1:        0.7812
ROC-AUC:   0.8349
Confusion Matrix:
[[ 74  41]
 [ 15 100]]

Fold 1 time: 42.57 minutes
Elapsed time: 42.57 minutes
Estimated time remaining: 170.27 minutes

========== Fold 2/5 ==========

Fold 2 - Epochs:  20%|██        | 1/5 [06:22<25:29, 382.33s/it]

Epoch 1/5 | Train Loss: 0.6038 | Val Loss: 0.6075 | Val Acc: 0.6870 | Val Recall: 0.8087 | Val F1: 0.7209 | Val AUC: 0.7377


Fold 2 - Epochs:  40%|████      | 2/5 [12:30<18:41, 373.88s/it]

Epoch 2/5 | Train Loss: 0.4995 | Val Loss: 0.5720 | Val Acc: 0.6957 | Val Recall: 0.8261 | Val F1: 0.7308 | Val AUC: 0.7652


Fold 2 - Epochs:  60%|██████    | 3/5 [18:41<12:25, 372.78s/it]

Epoch 3/5 | Train Loss: 0.4811 | Val Loss: 0.5290 | Val Acc: 0.7174 | Val Recall: 0.8957 | Val F1: 0.7601 | Val AUC: 0.7993


Fold 2 - Epochs:  80%|████████  | 4/5 [24:44<06:09, 369.00s/it]

Epoch 4/5 | Train Loss: 0.4598 | Val Loss: 0.5165 | Val Acc: 0.7391 | Val Recall: 0.9217 | Val F1: 0.7794 | Val AUC: 0.8144


Fold 2 - Epochs: 100%|██████████| 5/5 [30:20<00:00, 364.07s/it]


Epoch 5/5 | Train Loss: 0.4455 | Val Loss: 0.5244 | Val Acc: 0.7348 | Val Recall: 0.8783 | Val F1: 0.7681 | Val AUC: 0.8150


Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_2/fold_2_img_104_true_0_pred_0_prob_0.21.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_2/fold_2_img_133_true_0_pred_1_prob_0.65.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_2/fold_2_img_138_true_1_pred_1_prob_0.74.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_2/fold_2_img_179_true_1_pred_1_prob_0.62.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_2/fold_2_img_220_true_0_pred_0_prob_0.05.png

Best fold metrics:
Accuracy:  0.7391
Precision: 0.6752
Recall:    0.9217
F1:        0.7794
ROC-AUC:   0.8144
Confusion Matrix:
[[ 64  51]
 [  9 106]]

Fold 2 time: 30.82 minutes
Elapsed time: 73.39 minutes
Estimated time remaining: 110.08 minutes

========== Fold 3/5 ======

Fold 3 - Epochs:  20%|██        | 1/5 [05:53<23:33, 353.46s/it]

Epoch 1/5 | Train Loss: 0.5922 | Val Loss: 0.6468 | Val Acc: 0.6739 | Val Recall: 0.8696 | Val F1: 0.7273 | Val AUC: 0.6699


Fold 3 - Epochs:  40%|████      | 2/5 [11:37<17:23, 347.84s/it]

Epoch 2/5 | Train Loss: 0.5074 | Val Loss: 0.6143 | Val Acc: 0.6652 | Val Recall: 0.8522 | Val F1: 0.7179 | Val AUC: 0.6945


Fold 3 - Epochs:  60%|██████    | 3/5 [17:21<11:32, 346.01s/it]

Epoch 3/5 | Train Loss: 0.4825 | Val Loss: 0.6184 | Val Acc: 0.6783 | Val Recall: 0.8783 | Val F1: 0.7319 | Val AUC: 0.7216


Fold 3 - Epochs:  80%|████████  | 4/5 [23:05<05:45, 345.19s/it]

Epoch 4/5 | Train Loss: 0.4533 | Val Loss: 0.6062 | Val Acc: 0.7000 | Val Recall: 0.9130 | Val F1: 0.7527 | Val AUC: 0.7478


Fold 3 - Epochs: 100%|██████████| 5/5 [28:51<00:00, 346.35s/it]


Epoch 5/5 | Train Loss: 0.4492 | Val Loss: 0.6634 | Val Acc: 0.6913 | Val Recall: 0.9130 | Val F1: 0.7473 | Val AUC: 0.7592


Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_3/fold_3_img_69_true_1_pred_1_prob_0.76.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_3/fold_3_img_106_true_0_pred_0_prob_0.18.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_3/fold_3_img_124_true_0_pred_0_prob_0.08.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_3/fold_3_img_65_true_0_pred_0_prob_0.01.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_3/fold_3_img_20_true_0_pred_1_prob_0.55.png

Best fold metrics:
Accuracy:  0.7000
Precision: 0.6402
Recall:    0.9130
F1:        0.7527
ROC-AUC:   0.7478
Confusion Matrix:
[[ 56  59]
 [ 10 105]]

Fold 3 time: 29.34 minutes
Elapsed time: 102.73 minutes
Estimated time remaining: 68.49 minutes

========== Fold 4/5 =========

Fold 4 - Epochs:  20%|██        | 1/5 [05:56<23:45, 356.30s/it]

Epoch 1/5 | Train Loss: 0.6034 | Val Loss: 0.6063 | Val Acc: 0.7043 | Val Recall: 0.8696 | Val F1: 0.7463 | Val AUC: 0.7464


Fold 4 - Epochs:  40%|████      | 2/5 [11:37<17:22, 347.46s/it]

Epoch 2/5 | Train Loss: 0.5145 | Val Loss: 0.5226 | Val Acc: 0.7217 | Val Recall: 0.8870 | Val F1: 0.7612 | Val AUC: 0.8056


Fold 4 - Epochs:  60%|██████    | 3/5 [17:45<11:53, 356.92s/it]

Epoch 3/5 | Train Loss: 0.4875 | Val Loss: 0.5146 | Val Acc: 0.7696 | Val Recall: 0.9043 | Val F1: 0.7969 | Val AUC: 0.8181


Fold 4 - Epochs:  80%|████████  | 4/5 [23:51<06:00, 360.43s/it]

Epoch 4/5 | Train Loss: 0.4837 | Val Loss: 0.4911 | Val Acc: 0.7783 | Val Recall: 0.9304 | Val F1: 0.8075 | Val AUC: 0.8459


Fold 4 - Epochs: 100%|██████████| 5/5 [30:20<00:00, 364.14s/it]


Epoch 5/5 | Train Loss: 0.4638 | Val Loss: 0.4634 | Val Acc: 0.7826 | Val Recall: 0.9391 | Val F1: 0.8120 | Val AUC: 0.8535


Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_4/fold_4_img_227_true_1_pred_1_prob_0.90.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_4/fold_4_img_19_true_0_pred_1_prob_0.98.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_4/fold_4_img_102_true_1_pred_1_prob_0.68.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_4/fold_4_img_10_true_0_pred_0_prob_0.17.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_4/fold_4_img_150_true_1_pred_1_prob_0.91.png

Best fold metrics:
Accuracy:  0.7826
Precision: 0.7152
Recall:    0.9391
F1:        0.8120
ROC-AUC:   0.8535
Confusion Matrix:
[[ 72  43]
 [  7 108]]

Fold 4 time: 30.94 minutes
Elapsed time: 133.67 minutes
Estimated time remaining: 33.42 minutes

========== Fold 5/5 ========

Fold 5 - Epochs:  20%|██        | 1/5 [06:26<25:45, 386.31s/it]

Epoch 1/5 | Train Loss: 0.6067 | Val Loss: 0.6527 | Val Acc: 0.6565 | Val Recall: 0.6522 | Val F1: 0.6550 | Val AUC: 0.7209


Fold 5 - Epochs:  40%|████      | 2/5 [13:11<19:52, 397.63s/it]

Epoch 2/5 | Train Loss: 0.5076 | Val Loss: 0.6252 | Val Acc: 0.6609 | Val Recall: 0.7391 | Val F1: 0.6855 | Val AUC: 0.7236


Fold 5 - Epochs:  60%|██████    | 3/5 [19:37<13:04, 392.22s/it]

Epoch 3/5 | Train Loss: 0.4851 | Val Loss: 0.5719 | Val Acc: 0.7087 | Val Recall: 0.9304 | Val F1: 0.7616 | Val AUC: 0.7535


Fold 5 - Epochs:  80%|████████  | 4/5 [25:56<06:26, 386.92s/it]

Epoch 4/5 | Train Loss: 0.4601 | Val Loss: 0.5168 | Val Acc: 0.7391 | Val Recall: 0.9391 | Val F1: 0.7826 | Val AUC: 0.7966


Fold 5 - Epochs: 100%|██████████| 5/5 [32:22<00:00, 388.54s/it]


Epoch 5/5 | Train Loss: 0.4480 | Val Loss: 0.5207 | Val Acc: 0.7391 | Val Recall: 0.9043 | Val F1: 0.7761 | Val AUC: 0.8016


Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_5/fold_5_img_90_true_0_pred_0_prob_0.21.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_5/fold_5_img_16_true_1_pred_1_prob_0.71.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_5/fold_5_img_110_true_1_pred_0_prob_0.32.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_5/fold_5_img_141_true_0_pred_0_prob_0.11.png
Saving to: /Users/harryshield/Documents/Data Science/DS4002/Project 3/Gradcam_Outputs_DenseNet/fold_5/fold_5_img_116_true_1_pred_1_prob_0.69.png

Best fold metrics:
Accuracy:  0.7391
Precision: 0.6708
Recall:    0.9391
F1:        0.7826
ROC-AUC:   0.7966
Confusion Matrix:
[[ 62  53]
 [  7 108]]

Fold 5 time: 32.93 minutes
Elapsed time: 166.60 minutes
Estimated time remaining: 0.00 minutes

========== CROSS-VALIDATION S